# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ContGrid <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, debugging) {
    .Call(`_regnet_ContGrid`, xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, debugging)
}

ContGrid_MC <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, ncores, debugging) {
    .Call(`_regnet_ContGrid_MC`, xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, ncores, debugging)
}

LogitGrid <- function(x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method) {
    .Call(`_regnet_LogitGrid`, x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method)
}

LogitGrid_MC <- function(x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method, ncores) {
    .Call(`_regnet_LogitGrid_MC`, x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method, ncores)
}

RunCont <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method) {
    .Call(`_regnet_RunCont`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method)
}

RunCont_robust <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging) {
    .Call(`_regnet_RunCont_robust`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging)
}

RunLogit <- function(x, y, lamb1, lamb2, b, r, a, triRowAbsSums, p, alpha, method) {
    .Call(`_regnet_RunLogit`, x, y, lamb1, lamb2, b, r, a, triRowAbsSums, p, alpha, method)
}

RunNet <- function(x, y, lamb1, lamb2, b, r, a, p) {
    .Call(`_regnet_RunNet`, x, y, lamb1, lamb2, b, r, a, p)
}

RunMCP <- function(x, y, lambda, b, r, p) {
    .Call(`_regnet_RunMCP`, x, y, lambda, b, r, p)
}

RunElastic <- function(x, y, lambda, b, alpha, p) {
    .Call(`_regnet_RunElastic`, x, y, lambda, b, alpha, p)
}

RunSurv_robust <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging) {
    .Call(`_regnet_RunSurv_robust`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method, debugging)
}

RunSurv <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method) {
    .Call(`_regnet_RunSurv`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, triRowAbsSums, p, pc, method)
}

SurvCV <- function(Xc, Xg, Y, folds, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, ncores, debugging) {
    .Call(`_regnet_SurvCV`, Xc, Xg, Y, folds, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, ncores, debugging)
}

SurvGrid <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, method, debugging) {
    .Call(`_regnet_SurvGrid`, xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, method, debugging)
}

SurvGrid_MC <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, method, ncores, debugging) {
    .Call(`_regnet_SurvGrid_MC`, xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, method, ncores, debugging)
}

