# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunNet <- function(x, y, lam1, lam2, b, r, a, n, p) {
    .Call('regnet_RunNet', PACKAGE = 'regnet', x, y, lam1, lam2, b, r, a, n, p)
}

