# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ContGrid <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method) {
    .Call(`_regnet_ContGrid`, xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method)
}

ContGrid_MC <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, ncores) {
    .Call(`_regnet_ContGrid_MC`, xc, xg, y, x2, y2, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust, method, ncores)
}

LogitGrid <- function(x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method, ncores) {
    .Call(`_regnet_LogitGrid`, x, y, x2, y2, lamb1, lamb2, b, r, a, p, alpha, method, ncores)
}

RunCont <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method) {
    .Call(`_regnet_RunCont`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method)
}

RunCont_robust <- function(xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method) {
    .Call(`_regnet_RunCont_robust`, xc, xg, y, lamb1, lamb2, bc, bg, r, a, p, pc, method)
}

RunLogit <- function(x, y, lamb1, lamb2, b, r, a, p, alpha, method) {
    .Call(`_regnet_RunLogit`, x, y, lamb1, lamb2, b, r, a, p, alpha, method)
}

RunNet <- function(x, y, lamb1, lamb2, b, r, a, p) {
    .Call(`_regnet_RunNet`, x, y, lamb1, lamb2, b, r, a, p)
}

RunMCP <- function(x, y, lambda, b, r, p) {
    .Call(`_regnet_RunMCP`, x, y, lambda, b, r, p)
}

RunElastic <- function(x, y, lambda, b, alpha, p) {
    .Call(`_regnet_RunElastic`, x, y, lambda, b, alpha, p)
}

RunNetSurv <- function(xc, xg, y, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust) {
    .Call(`_regnet_RunNetSurv`, xc, xg, y, lamb1, lamb2, bc0, bg0, r, a, p, pc, robust)
}

RunMCPSurv <- function(xc, xg, y, lamb1, bc, bg, r, p, pc, robust) {
    .Call(`_regnet_RunMCPSurv`, xc, xg, y, lamb1, bc, bg, r, p, pc, robust)
}

RunLassoSurv <- function(xc, xg, y, lamb1, bc, bg, p, pc, robust) {
    .Call(`_regnet_RunLassoSurv`, xc, xg, y, lamb1, bc, bg, p, pc, robust)
}

NetGrid <- function(xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, ncores) {
    .Call(`_regnet_NetGrid`, xc, xg, y, x2, y2, lamb1, lamb2, bc, bg, r, a, p, pc, robust, ncores)
}

MCPGrid <- function(xc, xg, y, x2, y2, lamb1, bc, bg, r, p, pc, robust, ncores) {
    .Call(`_regnet_MCPGrid`, xc, xg, y, x2, y2, lamb1, bc, bg, r, p, pc, robust, ncores)
}

LassoGrid <- function(xc, xg, y, x2, y2, lamb1, bc, bg, p, pc, robust, ncores) {
    .Call(`_regnet_LassoGrid`, xc, xg, y, x2, y2, lamb1, bc, bg, p, pc, robust, ncores)
}

